let countryData;
let background;
let maxxdaddy;
let start;
let dialog;
let dialogText;
let startGame = false;
let timerBox;
let timerBar;
let timerBar2;
let country;
let lives = 5;
let timerCount = 0;
let attemptStarted = false;
let alertText;
let alertCounter = 5000;
let correctAnswers = [];
let countries;
let wait = false;
let cty;